sudo: required

services:
  - docker

before_install:
  - docker pull node:7.9

script:
  - echo $TRAVIS_BRANCH
  - docker run -t node:7.9 node -v

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker run -t node:7.9 node --help;
    fi
